### ISSUE TITLE
Disregarding Laguna Lake

### ISSUE THREAD

**Issue by ray-dino** [thinkingmachines/cartogramph#2]
Noticed that at several points, the code is checking if the Name is "Laguna Lake". Perhaps we can remove that data point at the beginning?

**Comment by stefsy** [comment]
@ray-dino can you reference the specific files and line to make it easier to find?

**Comment by ray-dino** [comment]
D'oh. Of course! This one is for lib/cartogramph.js.

**Comment by mikaaldaba** [comment]
@ray-dino it's hard to remove it because it will mess up the other provinces beside it. That's just how the topojson file is structured.
